import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import 'swiper/css';
import 'swiper/css/pagination';
import 'animate.css';
import '@vidstack/react/player/styles/default/theme.css';
import '@vidstack/react/player/styles/default/layouts/video.css';
import WhatsAppChat from "../components/WhatsAppChat";
import Image from "next/image";
import bgImg from '../assets/gradientbg.jpg'
import {NextUIProvider} from "@nextui-org/system";
import HeaderNavbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <NextUIProvider>
              <div className="bg">
                <Image className="h-screen" src={bgImg} alt="Background Image"></Image>
              </div>
                {/* <Header /> */}
                <HeaderNavbar />
              <div className="container">
                {children}
              </div>
              <WhatsAppChat />
          </NextUIProvider>
        </body>
    </html>
  );
}
