import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import 'swiper/css';
import 'swiper/css/pagination';
import 'animate.css';
import '@vidstack/react/player/styles/default/theme.css';
import '@vidstack/react/player/styles/default/layouts/video.css';
import WhatsAppChat from "../components/WhatsAppChat";
import Image from "next/image";
import bgImg from '../assets/gradientbg.jpg'
import {NextUIProvider} from "@nextui-org/system";
import HeaderNavbar from "../components/Navbar";
import i18nConfig from "@/i18nConfig";
import { dir } from "i18next";
import initTranslations from "../i18n";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default async function RootLayout({
  children, params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: any }
}>) {
  const nameSpaces = ['header']
  const { t, resources } = await initTranslations(locale, nameSpaces, null, null );

  return (
    <html lang={locale} dir={dir(locale)}>
        <body className={inter.className}>
          <NextUIProvider>
              <div className="bg">
                <Image className="h-screen" src={bgImg} alt="Background Image"></Image>
              </div>
                {/* <Header /> */}
                <HeaderNavbar home={t('home')} studies={t('studies')} contact={t('contact')} consultation={t('consultation')} />
              <div className="container">
                {children}
              </div>
              <WhatsAppChat />
          </NextUIProvider>
        </body>
    </html>
  );
}
