import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import 'swiper/css';
import 'swiper/css/pagination';
import 'animate.css';
import "animate.css/animate.compat.css"
import '@vidstack/react/player/styles/default/theme.css';
import '@vidstack/react/player/styles/default/layouts/video.css';
import WhatsAppChat from "../components/WhatsAppChat";
import Image from "next/image";
import bgImg from '../assets/gradientbg.jpg'
import {NextUIProvider} from "@nextui-org/system";
import HeaderNavbar from "../components/Navbar";
import i18nConfig from "@/i18nConfig";
import { dir } from "i18next";
import initTranslations from "../i18n";
import {ScrollShadow} from "@nextui-org/react";
import Footer from "../components/Footer";
import Head from "next/head";
// import { motion, AnimatePresence } from 'framer-motion';


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default async function RootLayout({
  children, params: { locale }
}: Readonly<{
  children: any;
  params: { locale: any }
}>) {
  const nameSpaces = ['header']
  const { t, resources } = await initTranslations(locale, nameSpaces, null, null );
  
  return (
    <html lang={locale} dir={dir(locale)}>

        {/* <Head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link href="https://fonts.googleapis.com/css2?family=Jomhuria&display=swap" rel="stylesheet" />
        </Head> */}

        <body>
          <NextUIProvider>
              <div className="bg">
                <Image className="h-screen" src={bgImg} alt="Background Image"></Image>
              </div>
                               
                <HeaderNavbar home={t('home')} studies={t('studies')} contact={t('contact')} consultation={t('consultation')} />
                  
                  <div className="min-h-screen">
                    {children}
                  </div>
                  
                  <WhatsAppChat />
                  <Footer />
                               
          </NextUIProvider>
        </body>
    </html>
  );
}
